//= include('plugins/normalizeconsole.js')
//= include('plugins/waiter.js')
//= include('plugins/big.brother.counters.js')
// = include('plugins/jquery.fancybox.js')
//= include('plugins/jquery.form.js')
//= include('plugins/jquery.ajax.form.loader.js')
